package Entities;
// default package
// Generated 12-may-2014 19:20:40 by Hibernate Tools 3.4.0.CR1

/**
 * FollowersId generated by hbm2java
 */
public class FollowersId implements java.io.Serializable {

	private int userId;
	private int followedId;

	public FollowersId() {
	}

	public FollowersId(int userId, int followedId) {
		this.userId = userId;
		this.followedId = followedId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getFollowedId() {
		return this.followedId;
	}

	public void setFollowedId(int followedId) {
		this.followedId = followedId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FollowersId))
			return false;
		FollowersId castOther = (FollowersId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getFollowedId() == castOther.getFollowedId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getFollowedId();
		return result;
	}

}
