package Entities;
// default package
// Generated 12-may-2014 19:20:40 by Hibernate Tools 3.4.0.CR1

/**
 * Followers generated by hbm2java
 */
public class FollowersEntity implements java.io.Serializable {

	private FollowersId id;

	public FollowersEntity() {
	}

	public FollowersEntity(FollowersId id) {
		this.id = id;
	}

	public FollowersId getId() {
		return this.id;
	}

	public void setId(FollowersId id) {
		this.id = id;
	}

}
