package Entities;
// default package
// Generated 12-may-2014 19:20:40 by Hibernate Tools 3.4.0.CR1

/**
 * ForwardsId generated by hbm2java
 */
public class ForwardsId implements java.io.Serializable {

	private int forwarderId;
	private int messageId;

	public ForwardsId() {
	}

	public ForwardsId(int forwarderId, int messageId) {
		this.forwarderId = forwarderId;
		this.messageId = messageId;
	}

	public int getForwarderId() {
		return this.forwarderId;
	}

	public void setForwarderId(int forwarderId) {
		this.forwarderId = forwarderId;
	}

	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ForwardsId))
			return false;
		ForwardsId castOther = (ForwardsId) other;

		return (this.getForwarderId() == castOther.getForwarderId())
				&& (this.getMessageId() == castOther.getMessageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getForwarderId();
		result = 37 * result + this.getMessageId();
		return result;
	}

}
