package Entities;
// default package
// Generated 12-may-2014 19:20:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Hashtags generated by hbm2java
 */
public class HashtagsEntity implements java.io.Serializable {

	private Integer id;
	private String hashtag;
	private int authorId;
	private Date creationDate;

	public HashtagsEntity() {
	}

	public HashtagsEntity(String hashtag, int authorId, Date creationDate) {
		this.hashtag = hashtag;
		this.authorId = authorId;
		this.creationDate = creationDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getHashtag() {
		return this.hashtag;
	}

	public void setHashtag(String hashtag) {
		this.hashtag = hashtag;
	}

	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
