package Entities;
// default package
// Generated 12-may-2014 19:20:40 by Hibernate Tools 3.4.0.CR1

/**
 * MessageHashtags generated by hbm2java
 */
public class MessageHashtagsEntity implements java.io.Serializable {

	private MessageHashtagsId id;

	public MessageHashtagsEntity() {
	}

	public MessageHashtagsEntity(MessageHashtagsId id) {
		this.id = id;
	}

	public MessageHashtagsId getId() {
		return this.id;
	}

	public void setId(MessageHashtagsId id) {
		this.id = id;
	}

}
