package Entities;
// default package
// Generated 12-may-2014 19:20:40 by Hibernate Tools 3.4.0.CR1

/**
 * MessageHashtagsId generated by hbm2java
 */
public class MessageHashtagsId implements java.io.Serializable {

	private int messageId;
	private int hashtagId;

	public MessageHashtagsId() {
	}

	public MessageHashtagsId(int messageId, int hashtagId) {
		this.messageId = messageId;
		this.hashtagId = hashtagId;
	}

	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	public int getHashtagId() {
		return this.hashtagId;
	}

	public void setHashtagId(int hashtagId) {
		this.hashtagId = hashtagId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MessageHashtagsId))
			return false;
		MessageHashtagsId castOther = (MessageHashtagsId) other;

		return (this.getMessageId() == castOther.getMessageId())
				&& (this.getHashtagId() == castOther.getHashtagId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMessageId();
		result = 37 * result + this.getHashtagId();
		return result;
	}

}
