package Entities;
// default package
// Generated 12-may-2014 19:20:40 by Hibernate Tools 3.4.0.CR1

/**
 * Users generated by hbm2java
 */
public class UsersEntity implements java.io.Serializable {

	private Integer id;
	private String name;
	private String alias;
	private String password;
	private String photo;

	public UsersEntity() {
	}

	public UsersEntity(String name, String alias, String password) {
		this.name = name;
		this.alias = alias;
		this.password = password;
	}

	public UsersEntity(String name, String alias, String password, String photo) {
		this.name = name;
		this.alias = alias;
		this.password = password;
		this.photo = photo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

}
